### ISSUE TITLE
‘NGX_HTTP_UPSTREAM_MAX_CONNS’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by panjunDev** [yzprofile/ngx_http_dyups_module#100]
hi,friends
i add ngx_http_dyups_module base on nginx（nginx-1.10.3）,got a error,here is msg:
../ngx_http_dyups_module/ngx_http_dyups_module.c: In function ‘ngx_dyups_init_upstream’:
../ngx_http_dyups_module/ngx_http_dyups_module.c:1540:19: error: ‘NGX_HTTP_UPSTREAM_MAX_CONNS’ undeclared (first use in this function)
                  |NGX_HTTP_UPSTREAM_MAX_CONNS
                   ^

**Comment by iandyh** [comment]
Hi

This requires Nginx 1.11.5. `max_conn` is a new option in upstream configuration provided in this version.

**Comment by panjunDev** [comment]
thks
