### ISSUE TITLE
unknown directive "dyups_interface" in /usr/local/nginx-1.12.2/conf/nginx.conf

### ISSUE THREAD

**Issue by panjunDev** [yzprofile/ngx_http_dyups_module#106]
这是我的configure参数：
configure arguments: --prefix=/usr/local/nginx-1.12.2 --with-stream --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-pcre --with-http_v2_module --add-module=/usr/local/ngx_devel_kit-0.3.0 --add-module=/usr/local/lua-nginx-module-0.10.9rc7 --add-module=/usr/local/nginx_upstream_check_module --add-module=/usr/local/nginx-http-concat --add-dynamic-module=/usr/local/ngx_http_dyups_module --add-module=/usr/local/lua-upstream-nginx-module/

这是我的配置文件：
 server {
        listen 8081;
         location / {
           dyups_interface;
          }
      }

已经包含了ngx_http_dyups_module，但是启动nginx时候报错。

**Comment by cuber** [comment]
```shell
--add-dynamic-module=/usr/local/ngx_http_dyups_module
```
你这编译的是个动态 so 扩展
加载的时候要在配置文件里写 `load_module /path/to/your/xxx.so`
