### ISSUE TITLE
写入dyups共享内存的数据，在健康检查页面不显示

### ISSUE THREAD

**Issue by lxmopensource** [yzprofile/ngx_http_dyups_module#114]
![image](https://user-images.githubusercontent.com/23723022/53852999-db008c00-3ffe-11e9-9678-61c1a19daa90.png)

在dyups的detail接口里面可以看到写入共享内存的数据

但是在upstream check status页面看不到数据
![image](https://user-images.githubusercontent.com/23723022/53853276-beb11f00-3fff-11e9-82d2-907098d746e1.png)

这个会跟什么有关？各位大神，解个惑。

**Comment by NeverRen** [comment]
dyups does not compatible with Tengine upstream health check

**Comment by lxmopensource** [comment]
> dyups does not compatible with Tengine upstream health check

嗯  已经解决了，在upsream check module 里面有个MAX DYNAMIC PEER的限制，把这个值放大就可以了。在未放大之前，到了5700多就会有问题。
