### ISSUE TITLE
和nginx_upstream_check_module没有一起生效

### ISSUE THREAD

**Issue by liutpmars** [yzprofile/ngx_http_dyups_module#119]
安装nginx-1.8.1，./configure --prefix=/usr/local/nginx  --add-module=../ngx_http_dyups_module-master/ --add-module=../nginx_upstream_check_module-master/
配置upstream如下，check模块并有生效，一个节点宕机后，每隔10秒会给宕机节点发一个请求，这个业务请求就丢失了。
看readme文档，下面这句是指可以和健康检查模块一起工作吗？还是我的版本和安装方式有问题？
It works well with patched nginx_upstream_check_module

```
upstream my-test.lietou.com {
        server 10.110.14.206:7347;
        server 10.110.14.130:7347;
        check interval=2000 rise=1 fall=2 timeout=1000 type=tcp;
}
server {
  listen     80;
  server_name  test.lietou.com;
  proxy_next_upstream off;
  set $access_filter "on";
  set $ups "my-test.lietou.com";

  location /{
    proxy_pass  http://$ups;
  }
}
```

**Comment by chobits** [comment]
你需要使用，yzprofile独立维护的upstream check模块，这个模块对upstream check已经修正过了。

https://github.com/yzprofile/nginx_upstream_check_module
