### ISSUE TITLE
TCP Proxy module support

### ISSUE THREAD

**Issue by chendo** [yzprofile/ngx_http_dyups_module#32]
It would be fantastic if this module could also update the upstreams in https://github.com/yaoweibin/nginx_tcp_proxy_module

**Comment by yzprofile** [comment]
I'm sorry, the upstreams of tcp module and http module are different,  and the tcp proxy module is a third-party module for Nginx.

I don't think supporting it in `http_dyups_module` is appropriate. 

Regards
