### ISSUE TITLE
health check doesn't work after updating upstream

### ISSUE THREAD

**Issue by bjrara** [yzprofile/ngx_http_dyups_module#33]
config/nginx.config file:
```
http {
    //...
    #add runtime upstream reconfiguration
    include upstream.conf;
    dyups_upstream_conf  upstream.conf;

    server {
        listen 8090;
        location / {
            dyups_interface;
        }
    }

server {
        listen       80;
        server_name  localhost;
        location / {
            proxy_pass http://cluster;
        }
        //...
    }
    //...
}
```
config/upstream.config file:
```
upstream cluster {
    server 127.0.0.1:8888;
    server 127.0.0.1:8889;
    check interval=3000 rise=2 fall=5 timeout=1000 type=http;
    check_http_send "GET / HTTP/1.0\r\n\r\n";
    check_http_expect_alive http_2xx http_3xx;
}
```

After running the command  ```curl -d "server 127.0.0.1:8088;server 127.0.0.1:8089;" 127.0.0.1:8090/upstream/cluster```, check health function stops working - no requests received by my  test clusters.

**Comment by bjrara** [comment]
problem solved. my fault, command error.

**Comment by gaoshangs** [comment]
I also encountered such a problem, share you command, thank you.

**Comment by bjrara** [comment]
post entity with full upstream content.
e.g.
curl -d "server 127.0.0.1:8088;server 127.0.0.1:8089;check interval=3000 rise=2 fall=5 timeout=1000 type=http; check_http_send "GET / HTTP/1.0\r\n\r\n"; check_http_expect_alive http_2xx http_3xx;" 127.0.0.1:8090/upstream/cluster

**Comment by gaoshangs** [comment]
thank you very much,work well.
