### ISSUE TITLE
您好，请教下安装时有报错

### ISSUE THREAD

**Issue by zacard-orc** [yzprofile/ngx_http_dyups_module#34]
adding module in ./ngx_http_dyups_module
: command not founddule/config: line 6: 
'/ngx_http_dyups_module/config: line 7: syntax error near unexpected token `{
'/ngx_http_dyups_module/config: line 7: `dyups_lua() {

**Comment by yzprofile** [comment]
请提供一下 hexdump -C 的内容，看起来像是有不可见字符。

谢谢
