### ISSUE TITLE
您好，请教lua中添加多个server问题

### ISSUE THREAD

**Issue by zhangxin2012** [yzprofile/ngx_http_dyups_module#35]
status, rv = dyups.delete("backend_aether")
    if status ~= 200 then
        ngx.print(status, rv)
        return
    end
    ngx.print("delete success")
    local status, rv = dyups.update("backend_aether", [[server 10.8.210.9:8880;server10.8.210.14:8880;]]);
   (这里status =200)     
     ...
注：backend_aether为一个upstream的名字
请问下 要添加多个server  是这么使用的吗？ 但结果貌似没有生效。

**Comment by yzprofile** [comment]
```
    server {
        listen   8080;

        location / {
            proxy_pass http://$host;
        }
    }
```
请使用变量来查找upstream
