### ISSUE TITLE
您好，请教两个问题

### ISSUE THREAD

**Issue by davidwudv** [yzprofile/ngx_http_dyups_module#36]
1.ngx_http_dyups_module.c的604和607行为何unlock之后又马上lock，这两行是不是多余的？
2.ngx_http_dyups_read_msg函数最后几行这样写会不会更高效些：
if (!ngx_shmtx_trylock(&shpool->mutex)){
        return;
}
ngx_http_dyups_read_msg_locked(ev);
ngx_shmtx_unlock(&shpool->mutex);

**Comment by yzprofile** [comment]
1. 是多余的
2. 当时这么写是为了每个worker在一次 timer 时都能读到数据。当然也可以选用 trylock。
这里调用不频繁，性能上不会有身影响。

欢迎提交 pull request

谢谢 :)

**Comment by davidwudv** [comment]
好的 :)
