### ISSUE TITLE
您好，请教一下关于ngx_dyups_sandbox_update的问题

### ISSUE THREAD

**Issue by davidwudv** [yzprofile/ngx_http_dyups_module#37]
在update配置的时候，我看到这函数内做了个沙盒更新，添加了一个_dyups_upstream_sandbox_的upstream项，但是马上又mark deleted了，紧接着后面调用ngx_dyups_find_upstream函数又会把它的内存池给释放掉了，那么这sandbox update的意义何在呢？

**Comment by yzprofile** [comment]
用来检查配置合法性
