### ISSUE TITLE
dyups mark up/down upstream server reports abnormal exits error

### ISSUE THREAD

**Issue by bjrara** [yzprofile/ngx_http_dyups_module#40]
在 mark up/down 一台 upstream server 的时候，发现 error log 里 dyups 报出以下的错误：

2015/08/12 19:27:54 [alert] 23935#0: [dyups] process start after abnormal exits
2015/08/12 19:27:56 [crit] 23935#0: open() "/opt/app/nginx/conf/dyupstream.conf" failed (2: No such file or directory)
2015/08/12 19:27:56 [crit] 23935#0: [dyups] process restore upstream failed

nginx.conf 下配置
dyups_upstream_conf  conf/dyupstream.conf 这个文件是不存在的。

我们发现，在 mark down 一台 server 的时候，命令在部分机器上生效，而在另一部分机器上失败。但是 在失败的机器上 dyups 仍旧返回 200。同时，在失败的机器上 healthcheck module 返回的 status 结果是 up。也就是说这个命令确实没有生效。

请问这个问题是否会是 dyupstream.conf 文件不存在导致的不稳定？
dyups 更改的 upstream 模型是否处于 shared_memory 中，如果 respawn 一个新的进程，是否会导致 upstream 内存中的更改丢失。

另外，dyups_upstream_conf 是否支持path的正则匹配，例如 upstream_confs/*

**Comment by bjrara** [comment]
而且这个错误频繁出现

**Comment by yzprofile** [comment]
从你的日志文件中可以看到是在进程异常退出之后尝试从文件恢复upstream没有找到配置文件。
upstream list 不是存在共享内存里的，异常退出时会导致丢失。
后续有计划把它写入共享内存，不过最近没有时间来搞。

**Comment by bjrara** [comment]
dyups_upstream_conf 是否支持path的正则匹配，例如 upstream_confs/* 
我们有很多 upstream 的配置，是否可以通过文件通配符包含所有 conf 文件？

**Comment by yzprofile** [comment]
不支持的。后续会使用共享内存来做处理，从而去掉这个指令。
当然也欢迎 pull request。

谢谢

2015-08-13 10:33 GMT+08:00 bjrara <notifications@github.com>:

**Comment by bjrara** [comment]
今天用 gdb backtrace 了一下，发现在调用 dyups 的时候，会导致 spdy 模块 core dump。
(fyi 我使用的 tengine 配置了 spdy 和 openssl 模块。)

以下是 gdb 报出的错误：
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004c1f4e in ngx_http_spdy_state_data (sc=Cannot access memory at address 0xffffffffffffff88
) at src/http/ngx_http_spdy_v3.c:1495
1495	        return ngx_http_spdy_state_save(sc, pos, end,
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64
(gdb) backtrace full
#0  0x00000000004c1f4e in ngx_http_spdy_state_data (sc=Cannot access memory at address 0xffffffffffffff88
) at src/http/ngx_http_spdy_v3.c:1495
        size = <error reading variable size (Cannot access memory at address 0xffffffffffffff90)>
        n = <error reading variable n (Cannot access memory at address 0xffffffffffffff98)>
        buf = <error reading variable buf (Cannot access memory at address 0xffffffffffffffa0)>
        rc = <error reading variable rc (Cannot access memory at address 0xffffffffffffffa8)>
        complete = <error reading variable complete (Cannot access memory at address 0xffffffffffffffb0)>
        rev = <error reading variable rev (Cannot access memory at address 0xffffffffffffffb8)>
        tf = <error reading variable tf (Cannot access memory at address 0xffffffffffffffc0)>
        r = <error reading variable r (Cannot access memory at address 0xffffffffffffffc8)>
        stream = <error reading variable stream (Cannot access memory at address 0xffffffffffffffd0)>
        rb = <error reading variable rb (Cannot access memory at address 0xffffffffffffffd8)>
        clcf = <error reading variable clcf (Cannot access memory at address 0xffffffffffffffe0)>
        sscf = <error reading variable sscf (Cannot access memory at address 0xffffffffffffffe8)>
Cannot access memory at address 0x8

请帮忙看下，dyups 是否会导致以上错误的发生？

**Comment by bjrara** [comment]
Problem resolved after updating Tengine to 2.1.0/2.1.1.
