### ISSUE TITLE
When used domain in the upstream , there are some problems 

### ISSUE THREAD

**Issue by wangfakang** [yzprofile/ngx_http_dyups_module#41]
ｈｉ ＠yzprofile:
### 场景：

　当我使用如下配置的时候，访问相应的api: /detail 或　/upstream/bar其结果都是：
　`
bar      
server 61.135.169.121:80      
server 127.0.0.1:80      
server 127.0.0.1:81      
`
### 问题：

　为什么查看到的域名www.baidu.com的ｉｐ只有一个，实际是有两个的，此时dynamic upstream dns其实是生效的，因为访问的时候是代理到bar然后看日志都可以看到该域名对应的两个ip.　
### 关联：

　对了，我最近在agentzh的ngx_lua_upstream_module的基础上实现了针对于某一个upstream的members的动态管理(https://github.com/SinaMSRE/lua-upstream-ngianx-module)，但是现在不足的是：只是对当前的ｗｏｒｋ进程生效，其他的ｗｏｒｋ进程相应信息没有同步，（我实现的基本原理就是找到相应upstream后段peers的数据结构，然后在其指针指向的空间去增加server或是删除server,开始的时候几个work进程从master进程进程过来的空间由于没有写数据，所以是共享的，但是现在我对每一个ｗｏｒｋ进程的相应空间修改了就发生了＂写时拷贝＂，所以就只有一个ｗｏｒｋ进程真正的生效了）　不知道你有没有什么好的办法来解决这个？ 多谢指导　：）．
目前自己想了两个：
   (1)利用其进程间通信进行ｗｏｒｋ进程之间信息同步．
  (２)使用一块共享类存，要更新的数据都放在share mm上，然后ｗｏｒｋ进程定时向ｍｍ拉取．
### 配置文件:

```
server {
    listen   800;
    location / { 
        set $test               "bar";
        proxy_pass           http://$test;
    }
}   
```

   upstream bar {
        server www.baidu.com;
        server 127.0.0.1:80;
        server 127.0.0.1:81;
   }

**Comment by yzprofile** [comment]
upstream {} 配置的域名是通过 ngx_parse_url 来做的。最终只会拿 `gethostbyname` 第一个结果。

dyups 模块进程间通讯是通过共享内存和定时器读取消息来做的。

**Comment by wangfakang** [comment]
谢谢你的及时回复．　那现在相应的api: /detail 或　/upstream/[upsname] 表示的逻辑（功能）就是获取upstream对应的全部servers对嘛？　但是其域名所对应的server都解析出来了，虽然最后（解析出来的多个server随机排序，然后选择第一个）只会定向到后端的一个peer上． 我觉得这个时候应该都输出来才更符合点恩？你觉得恩？

**Comment by yzprofile** [comment]
这个逻辑是在 Nginx 解析配置文件里逻辑来做的，为了不 patch Nginx 的核心代码这块儿逻辑没法改变。
