### ISSUE TITLE
Dockerfile error with git apply of patch

### ISSUE THREAD

**Issue by davetropeano** [yzprofile/ngx_http_dyups_module#42]
The `docker build` fails on the wget of the 2.0.3 version of the patch. 

The patch file is not versioned but even if you change the Dockerfile to just use the .patch filename as is the docker build still fails with the message:

```
error: patch failed: src/http/ngx_http_upstream.h:1
error: src/http/ngx_http_upstream.h: patch does not apply
error: patch failed: src/http/ngx_http_upstream_check_module.c:98
error: src/http/ngx_http_upstream_check_module.c: patch does not apply
```

**Comment by yzprofile** [comment]
Sorry for that.

Tengine already merged the dyups module, so I don't provide the patch anymore.
