### ISSUE TITLE
Dynamic change not working

### ISSUE THREAD

**Issue by radut** [yzprofile/ngx_http_dyups_module#43]
Hi,
I change the servers from dyups but the request always goes to the ones defined in upstream.conf, they are not updated dynamically as the module stated, I have the folowing 

     server {
	listen 9090 default_server;

         location / {
           proxy_pass http://balancer;
         }
    }

     server {
     listen 9091 default_server;
        location / {
            return 200 "first";
        }
     }
     server {
        listen 9092 default_server;
        location / {
              return 200 "second";
         }
       }

my upstream.conf

    upstream balancer {
        server 127.0.0.1:9091;
        server 127.0.0.1:9092;
    }

    $curl http://dyups/upstream/balancer
    server 127.0.0.1:9091
    server 127.0.0.1:9092

    $ curl -d 'server 127.0.0.1:9092;' http://dyups/upstream/balancer
    success

    $ curl http://dyups/upstream/balancer
    server 127.0.0.1:9092

even so 

    $ curl http://localhost:9090
     first
     $ curl http://localhost:9090
     first
     $ curl http://localhost:9090
     second
     $ curl http://localhost:9090
    first

so the change is not taken into account

**Comment by yzprofile** [comment]
```
 server {
        listen   8080;

        location / {
            set $ups balancer;
            proxy_pass http://$ups;
        }
    }

```

Please use nginx variable to do proxy_pass.

**Comment by radut** [comment]
it worked; thank you !!
