### ISSUE TITLE
Combining upstream and domain conflicts with proxy_pass

### ISSUE THREAD

**Issue by bobrik** [yzprofile/ngx_http_dyups_module#45]
We use domain names as upstream names for late binding, like this:

```
set $where myapp.com;
proxy_pass http://$where;
```

Upstream `myapp.com` is created with `dyups` and can be absent at config parse time.

Now you can also have `proxy_pass http://myapp.com` somewhere in your configs. This is fine (or not) until you reload nginx. When you do reload, upstream `myapp.com` disappears from upstream list, even though it is present in config files. Restart makes upstream reappear again.

I'm not sure how to approach this issue other than avoid using dynamic upstream names directly.

**Comment by yzprofile** [comment]
Yes. It's an issue in this version, the upstream is in the memory.

It's better adding upstream into nginx config before you call the DYUPS api.

**Comment by bobrik** [comment]
I do add upstream into nginx config.
