### ISSUE TITLE
performance of dynamic adding upstream than reload nginx

### ISSUE THREAD

**Issue by xiaokai-wang** [yzprofile/ngx_http_dyups_module#46]
As you say, dynamic adding upstream needn't reload nginx. 

All we know, reloading nginx little decrease nginx performace.

So, dose dyups_module effect the nginx performace? or than 'nginx reload' better or worse?

**Comment by yzprofile** [comment]
Worse

**Comment by xiaokai-wang** [comment]
Now, adding backend servers or removing need reload nginx, frequently reloading nginx effect the nginx performance, does it?

I am doing a module that pull upstream servers from consul timely, needn't reload nginx. Do you think that is necessary?

Module address: https://github.com/weibocom/nginx-upsync-module;
If you have time, please have a look, any advice is appreciated.

**Comment by yzprofile** [comment]
Reloading doesn't slow down Nginx, But the old worker will not exit immediately before all connection is closed, After high frequency reloading, a large number of workers will cause OOM.

Syncing upstream from Consul or Etcd is a good idea, We planed that long ago, but no time to do that.

**Comment by xiaokai-wang** [comment]
Thanks, yzprofile.

I will improve it, next.

**Comment by noname007** [comment]
这个功能搞得怎么样了。：）

**Comment by noname007** [comment]
@xiaokai-wang

**Comment by xiaokai-wang** [comment]
@noname007 done.
 You can have a try https://github.com/weibocom/nginx-upsync-module
