### ISSUE TITLE
max_conns not support

### ISSUE THREAD

**Issue by millken** [yzprofile/ngx_http_dyups_module#49]
````
server 127.0.0.1:81; server 127.0.0.1:82 max_conns=1;
````
server return  502, remove and return 200

nginx log 
````
invalid parameter "max_conns=1" in command line
````

**Comment by millken** [comment]
```sticky cookie ``` also not supprt

**Comment by yzprofile** [comment]
These directives are belong to `Nginx Plus`,  not supported in community version.
