### ISSUE TITLE
dyups process start after abnormal exits

### ISSUE THREAD

**Issue by chenfz** [yzprofile/ngx_http_dyups_module#50]
RHEL7.2 + nginx 1.9.11 + 编译dyups模块，在启动nginx服务后，在error日志里会出现报错：
2016/03/02 12:58:52 [alert] 8412#8412: worker process 10652 exited on signal 11 (core dumped)
2016/03/02 12:58:52 [alert] 8412#8412: shared memory zone "ngx_http_dyups_module#1" was locked by 10652
2016/03/02 12:58:52 [alert] 10654#10654: [dyups] process start after abnormal exits

相同的编译参数在rhel6+nginx 1.4.4 + 编译dyups模块，是可以用的

**Comment by yzprofile** [comment]
Could you please provide the configure options and nginx.conf.

Thanks.

**Comment by chenfz** [comment]
configure:
./configure \
    --add-module=%{_builddir}/%{srcname}-%{version}/naxsi-0.54/naxsi_src \
    --prefix=%{_prefix} \
    --sbin-path=%{sbin_path}/nginx \
    --conf-path=%{conf_path}/nginx.conf \
    --error-log-path=%{log_path}/error.log \
    --http-log-path=%{log_path}/access.log \
    --http-client-body-temp-path=%{nginx_tmp}/client_body \
    --http-proxy-temp-path=%{nginx_tmp}/proxy_temp \
    --http-fastcgi-temp-path=%{nginx_tmp}/fastcgi \
    --http-uwsgi-temp-path=%{nginx_tmp}/uwsgi \
    --http-scgi-temp-path=%{nginx_tmp}/scgi \
    --pid-path=%{_localstatedir}/run/nginx.pid \
    --lock-path=%{_localstatedir}/lock/subsys/nginx \
    --user=%{nginx_user} \
    --group=%{nginx_group} \
    --with-file-aio \
    --with-ipv6 \
    --with-threads \
    --with-http_v2_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-http_ssl_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_xslt_module \
    --with-http_image_filter_module \
    --with-http_geoip_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gzip_static_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_degradation_module \
    --with-http_stub_status_module \
    --with-http_perl_module \
    --with-http_gunzip_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-debug \
    --with-cc-opt="%{optflags} $(pcre-config --cflags) -I %{include_path}" \
    --with-ld-opt="-Wl,-E -L %{lib_path}" \
    --add-module=%{_builddir}/%{srcname}-%{version}/ngx_devel_kit-0.2.19 \
    --add-module=%{_builddir}/%{srcname}-%{version}/lua-nginx-module-0.10.1rc0 \
    --add-module=%{_builddir}/%{srcname}-%{version}/set-misc-nginx-module-0.23 \
    --add-module=%{_builddir}/%{srcname}-%{version}/headers-more-nginx-module-0.26 \
    --add-module=%{_builddir}/%{srcname}-%{version}/echo-nginx-module-0.58 \
    --add-module=%{_builddir}/%{srcname}-%{version}/memc-nginx-module-0.16 \
    --add-module=%{_builddir}/%{srcname}-%{version}/redis2-nginx-module-0.12 \
    --add-module=%{_builddir}/%{srcname}-%{version}/ngx_cache_purge-2.3 \
    --add-module=%{_builddir}/%{srcname}-%{version}/nginx-push-stream-module-0.5.1 \
    --add-module=%{_builddir}/%{srcname}-%{version}/ngx_http_dyups_module-0.2.8 \
    --add-module=%{_builddir}/%{srcname}-%{version}/iconv-nginx-module-0.11 \
    --with-openssl=%{_builddir}/%{srcname}-%{version}/openssl-1.0.2d


nginx.conf:
user  nginx;
worker_rlimit_nofile  51200;
worker_processes  8;

pid     /opt/logs/nginx/nginx.pid;

events {
        worker_connections  10240;
        use  epoll;
}

http {
        server_tokens off;
        include       /opt/nginx/conf/mime.types;
        log_subrequest on;
        default_type  text/plain;

        log_format  main        '$remote_addr - $remote_user [$time_local] $host "$request" '
                                '"$status" $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for" ';

        log_format  debug       '$remote_addr - $remote_user [$time_local] $host "$request" '
                                '"$status" $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for" <$upstream_http_host> ($upstream_addr) $server_name $document_root "$fastcgi_script_name" {$query_string} $upstream_response_time $upstream_status $uri $request_uri';

        log_format  hadoop      '$remote_addr - $remote_user [$time_local] $host "$request" '
                                '"$status" $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for" "$server_name" "$upstream_addr" "$request_time"';


        access_log  /opt/logs/nginx/access.log  hadoop;
        error_log  /opt/logs/nginx/error.log;


        dyups_upstream_conf /opt/nginx/conf/upstream.conf;
        include /opt/nginx/conf/upstream.conf;
        dyups_shm_zone_size 64m;
        dyups_trylock on;

        lua_code_cache on;
        lua_package_path '/opt/nginx/conf/lua/?.lua;;';

        init_by_lua_file '/opt/nginx/conf/lua/init.lua';

        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;

        keepalive_timeout       15;
        send_timeout            1m;
        client_body_timeout     30;
        client_header_timeout   30;

        gzip on;
        gzip_vary on;
        gzip_min_length         1k;
        gzip_buffers            4 8k;
        gzip_http_version       1.1;
        gzip_comp_level         5;
        gzip_types              text/plain application/x-javascript text/css application/xml application/json;

        server_names_hash_max_size      512;
        server_names_hash_bucket_size   128;

        client_header_buffer_size       8k;
        client_max_body_size            200m;
        client_body_buffer_size 128k;
        large_client_header_buffers     4 4k;
        request_pool_size               1024k;
        connection_pool_size            512;

        output_buffers                  1 1024k;
        postpone_output                 1460;
        ignore_invalid_headers          on;

        proxy_redirect          off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_next_upstream     http_502 error timeout invalid_header;

        proxy_connect_timeout   15;
        proxy_send_timeout      30;
        proxy_read_timeout      300;

        proxy_buffer_size       8k;
        proxy_buffers           8 32k;
        proxy_busy_buffers_size 64k;

        proxy_headers_hash_bucket_size  64;
        proxy_headers_hash_max_size     512;

        proxy_ignore_client_abort       on;
        proxy_temp_file_write_size      64k;
        proxy_max_temp_file_size        0k;
        proxy_hide_header               Via;
        proxy_http_version 1.1;
        #proxy_set_header Connection "";

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      "";
    }

        fastcgi_connect_timeout 15;
        fastcgi_read_timeout 30;
        fastcgi_send_timeout 15;

        fastcgi_ignore_client_abort  on;


        more_set_headers 'My-app : $upstream_status from $upstream_addr';
        charset off;
        #add_header      X-Server        $server_addr;

        add_header      X-Server        192.168.1.1;

        include /opt/nginx/conf/vhosts/*.conf;

        server {

                listen 80;
                listen 443;

                server_name *.*;

                location / {
                        proxy_set_header        Host $host;
                        proxy_set_header        X-Real-IP $remote_addr;
                        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header        Upgrade $http_upgrade;
                        proxy_set_header        Connection $connection_upgrade;
                        proxy_pass http://$host;
                }

                include /opt/nginx/conf/mod/spider/robots;
                include /opt/nginx/conf/mod/spider/spider;
        }




        server {
                listen          8888;
                access_log      off;

                location /nginx_status {
                        stub_status     on;
                        allow           10.0.0.0/8;
                        deny            all;
                }
#                include /opt/nginx/conf/mod/eye/eye-status;
        }

        server {
                listen 8080;
                location / {
                        dyups_interface;
                        access_log  /opt/logs/nginx/dyups_interface-access.log  hadoop;
                        error_log  /opt/logs/nginx/dyups_interface-error.log;
                }
        }

#        include /opt/nginx/conf/mod/eye/eye;
        include /opt/nginx/conf/vhosts/*.conf;
}

**Comment by yzprofile** [comment]
Fixed, Thanks for your report.
