### ISSUE TITLE
使用dyups后的nginx请求处理问题

### ISSUE THREAD

**Issue by barryz** [yzprofile/ngx_http_dyups_module#51]
你好，我有个问题，在配置了dyups的情况下，我通过restful api将某台server下线，在下线的同时，恰好有个请求发送到此台server上，当server处理完请求准备响应时，此时upstream内已无此台server，那么这个响应该如何处理？

**Comment by yzprofile** [comment]
响应不受影响。

调用删除接口后，dyups 只是将 upstream 标记为下线，原有连接和请求继续处理，当 upstream 上请求时处理完毕后才删除 upstream。

**Comment by barryz** [comment]
回复很快！谢谢！！
