### ISSUE TITLE
make failed, ngx_dyups_mark_upstream_delete undefined

### ISSUE THREAD

**Issue by itxx00** [yzprofile/ngx_http_dyups_module#53]
Hello, any suggestion? thanks

```
objs/addon/ngx_http_dyups_module/ngx_http_dyups_module.o: In function `ngx_dyups_mark_upstream_delete':
/data/compile/nginx/bundle/ngx_http_dyups_module/ngx_http_dyups_module.c:1626: undefined reference to `ngx_http_upstream_check_delete_dynamic_peer'
collect2: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/data/compile/nginx/build/nginx-1.9.7'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/data/compile/nginx/build/nginx-1.9.7'
make: *** [all] Error 2
make failed
```

**Comment by yzprofile** [comment]
It's not compatible with [nginx_upstream_check_module](https://github.com/yaoweibin/nginx_upstream_check_module),  please use [tengine](https://github.com/alibaba/tengine). 

And I will fork `nginx_upstream_check_module` and try to fix it.

Thanks for your report.

**Comment by itxx00** [comment]
@yzprofile , thanks for your hard work :-)

**Comment by yzprofile** [comment]
https://github.com/yzprofile/nginx_upstream_check_module

and pull `dyups` repo again.

**Comment by itxx00** [comment]
works well now! thanks again. :-)
