### ISSUE TITLE
模块没有产生实际效果！！！！！！

### ISSUE THREAD

**Issue by Michael754267513** [yzprofile/ngx_http_dyups_module#54]
dear ：
    当我后端添加两个节点，然后在两个节点添加不同的静态文件，表示区别，配置完毕查看状态都是ok的！ 然后我就开始测试，当我踢掉其中一台，通过统计只有一台，但是我访问，一样可以访问到两个不同的页面，也就是说这个模块没有生效，这个问题有测试过吗？
下面是我测试过程以及配置文件！！！！

```
[root@QA-PUB01 test]# curl 127.0.0.1:8888/detail
rundeck
server 192.168.2.200:80
server 192.168.12.186:8080

[root@QA-PUB01 test]# curl 192.168.12.186:8080/status.jsp
Running1111

[root@QA-PUB01 test]# curl 192.168.2.200:80/status.jsp
Running

[root@QA-PUB01 test]# curl -d "server 192.168.2.200:80;" 127.0.0.1:8888/upstream/rundeck
success[root@QA-PUB01 test]127.0.0.1:8888/detail
rundeck
server 192.168.2.200:80

[root@QA-PUB01 test]# curl 192.168.12.186/status.jsp
Running

<!-- qa-pub01 Wed, 04 May 2016 09:07:08 GMT -->
[root@QA-PUB01 test]# curl 192.168.12.186/status.jsp
Running1111

<!-- qa-pub01 Wed, 04 May 2016 09:07:09 GMT -->
[root@QA-PUB01 test]# curl -d "server 192.168.12.186:8080;" 127.0.0.1:8888/upstream/rundeck
success[root@QA-PUB01 test]127.0.0.1:8888/detail
rundeck
server 192.168.12.186:8080

[root@QA-PUB01 test]# curl 192.168.12.186/status.jsp
**Running**

<!-- qa-pub01 Wed, 04 May 2016 09:08:02 GMT -->
[root@QA-PUB01 test]# curl 192.168.12.186/status.jsp
**_Running1111_**

<!-- qa-pub01 Wed, 04 May 2016 09:08:03 GMT -->

__________________________________________________________--
upstream rundeck {
        #consistent_hash $request_uri;
        server 192.168.2.200:80;
        server 192.168.12.186:8080;
        #session_sticky;

        #check interval=3000 rise=3 fall=2 timeout=2000 type=http; 
        #check_http_send "GET /status.jsp HTTP/1.0\r\n\r\n"; 
        #check_http_expect_alive http_2xx http_3xx; 
}
________________________________________________________-
server {
        listen  8888;
        server_name     127.0.0.1;
        location / {
                 dyups_interface;
        }
}__________________________________________________________

```

**Comment by yzprofile** [comment]
```
proxy_pass http://$host;
```

**Comment by Michael754267513** [comment]
listen  80;
        server_name     192.168.12.186;
        error_page  404 /404.html;
        client_max_body_size 30m;
        location / {
                #limit_req zone=one burst=100;
                limit_req zone=two burst=5  forbid_action=/500.htm;
                include proxy_opt.conf;
                proxy_pass http://rundeck/;
        } 
 是有的！不然我直接访问代理地址也不会得到两个不同的结果

**Comment by yzprofile** [comment]
https://github.com/yzprofile/ngx_http_dyups_module/issues/43

**Comment by Michael754267513** [comment]
set $host1 rundeck;
  proxy_pass http://$host1;
  设置也没有用~

**Comment by yzprofile** [comment]
配置文件贴全

**Comment by Michael754267513** [comment]
upstream rundeck {
        #consistent_hash $request_uri;
        server 192.168.2.200:80;
        server 192.168.12.186:8080;
        #session_sticky;
        #check interval=3000 rise=3 fall=2 timeout=2000 type=http;
        #check_http_send "GET /status.jsp HTTP/1.0\r\n\r\n";
        #check_http_expect_alive http_2xx http_3xx;
}

server {
        listen  80;
        server_name     192.168.12.186 www.qa.xjh.com;
        error_page  404 /404.html;
        location / {
                #limit_req zone=one burst=100;
                #limit_req zone=two burst=5  forbid_action=/500.htm;
                include proxy_opt.conf;
                set $host1 rundeck;
                proxy_pass http://$host1;
        }
         location ~ /purge(/.*) {
            allow            127.0.0.1;
            allow            192.168.2.0/24;
            deny            all;
            proxy_cache_purge    www.qa.xjh.com   $host$1$is_args$args;
        }
}

server {
        listen  8888;
        server_name     127.0.0.1;
        location / {
                 dyups_interface;
        }
}


ngx_http_dyups_module (shared, 3.1) 模块

**Comment by yzprofile** [comment]
没看出哪里有问题，

请问 https://github.com/yzprofile/ngx_http_dyups_module#config-example
示例配置在你那边是否有效？

**Comment by Michael754267513** [comment]
官方是列配置，报错。一直都有，nginx start一直卡住，但是可以访问，错误日志一直存在
2016/05/06 09:06:03 [info] 1514#0: [dyups] has 2 upstreams, 0 static, 0 deleted, all 2
2016/05/06 09:06:03 [info] 1517#0: [dyups] has 2 upstreams, 0 static, 0 deleted, all 2
修改官方默认，上面报错一直存在，测试效果失败！(采用tengine2.1.2，加载方式share)
        location / {
           set $www host1;
            proxy_pass http://$www;
        }
[root@QA-PUB01 sbin]# !cu
curl 127.0.0.1:8088
8088[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8088[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8089[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8088[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8089[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8089[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8088[root@QA-PUB01 sbin]# curl 127.0.0.1:8081/detail
host1
server 127.0.0.1:8088
server 127.0.0.1:8089

[root@QA-PUB01 sbin]# curl -d "server 127.0.0.1:8088;" 127.0.0.1:80801/upstream/host1
curl: (3) Port number too large: 80801
[root@QA-PUB01 sbin]# curl -d "server 127.0.0.1:8088;" 127.0.0.1:8081/upstream/host1
success[root@QA-PUB01 sbin]127.0.0.1:8081/detail
host1
server 127.0.0.1:8088

[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8089[root@QA-PUB01 sbin]# 
[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8089[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8088[root@QA-PUB01 sbin]# curl 127.0.0.1:8080
8088

**Comment by yzprofile** [comment]
1.
```
2016/05/06 09:06:03 [info] 1514#0: [dyups] has 2 upstreams, 0 static, 0 deleted, all 2
2016/05/06 09:06:03 [info] 1517#0: [dyups] has 2 upstreams, 0 static, 0 deleted, all 2
```

他们是 info 日志，不是错误日志，定时打印状态出来的。

2.
示例配置里有设置 
```
daemon off;
```
所以你看起来是一直卡住


3. 请仔细检查你的配置文件。

4. 请使用 markdown 格式来提交 issue. 提交前请预览一下他们。

**Comment by mliu111477** [comment]
@Michael754267513 您现在解决了么？我现在也存在restful接口操作后，查询后没有问题。但是nginx没有生效。。。
