### ISSUE TITLE
［在线等］ngx_http_dyups_module Added add/del upstream 疑问！

### ISSUE THREAD

**Issue by guozhouwei** [yzprofile/ngx_http_dyups_module#55]
嗨～
我想动态添加upstream，或者删除 等，在删除和添加前先修改upstream 数据，如下：

```
server {
            listen 8081;
            location / {
            content_by_lua '
                ngx.log(ngx.ERR, "here!!!************")
                    local dyups = require "ngx.dyups"
                ngx.print("here!!!")
                    local status, rv = dyups.update("test", [[server 127.0.0.1:8088;]]);
                ngx.print(status, rv)
                    if status ~= ngx.HTTP_OK then
                        ngx.print(status, rv)
                        return
                    end
                    ngx.print("update success")

                    status, rv = dyups.delete("test")
                    if status ~= ngx.HTTP_OK then
                        ngx.print(status, rv)
                        return
                    end
                    ngx.print("delete success")
            ';
                    dyups_interface;  //upstream 接口
            }
        }
```

我采用的是openresty
执行报如下错误：

```
==> error.log <==
2016/05/09 15:26:13 [error] 12279#0: *1 [lua] content_by_lua(nginx.conf:142):2: here!!!************, client: 127.0.0.1, server: , request: "POST /upstream/dyhost HTTP/1.1", host: "127.0.0.1:8081"
2016/05/09 15:26:13 [error] 12279#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:142):3: module 'ngx.dyups' not found:
    no field package.preload['ngx.dyups']
    no file '../lib/ngx/dyups.lua'
    no file '/usr/local/openresty/lualib/ngx/dyups.lua'
    no file '/usr/local/openresty/lualib/ngx/dyups/init.lua'
    no file './ngx/dyups.lua'
    no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta1/ngx/dyups.lua'
    no file '/usr/local/share/lua/5.1/ngx/dyups.lua'
    no file '/usr/local/share/lua/5.1/ngx/dyups/init.lua'
    no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/dyups.lua'
    no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/dyups/init.lua'
    no file '/usr/local/openresty/lualib/ngx/dyups.so'
    no file './ngx/dyups.so'
    no file '/usr/local/lib/lua/5.1/ngx/dyups.so'
    no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx/dyups.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/usr/local/openresty/lualib/ngx.so'
    no file './ngx.so'
    no file '/usr/local/lib/lua/5.1/ngx.so'
    no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
    [C]: in function 'require'
    content_by_lua(nginx.conf:142):3: in function <content_by_lua(nginx.conf:142):1>, client: 127.0.0.1, server: , request: "POST /upstream/dyhost HTTP/1.1", host: "127.0.0.1:8081"
```

**Comment by guozhouwei** [comment]
You should add the directive dyups_interface; in you config file.

如何 添加？

**Comment by yzprofile** [comment]
示例配置中有演示 Lua 的接口，若要使用 Lua API 需要和 Lua 模块一起编译才可以。
如果不需要的话，可以把示例配置里的 Lua 依赖删除。

**Comment by guozhouwei** [comment]
您的意思是我要加入下面这两个module码？

--add-module=/usr/local/src/ngx_devel_kit 
--add-module=/usr/local/src/lua-nginx-module

**Comment by yzprofile** [comment]
可以贴一下您的 ./configure 参数和输出，谢谢

**Comment by guozhouwei** [comment]
./configure \
--with-luajit \
--with-openssl=/Users/helloworld/openresty/servers/bundle/openssl-1.0.2g \
--with-http_ssl_module --with-http_sub_module \
--with-http_stub_status_module \
--with-http_gzip_static_module \
--with-pcre=/Users/helloworld/pcre/pcre-8.37 \
--add-module=/Users/helloworld/openresty/servers/openresty-1.9.7.4/ngx_http_dyups_module

**Comment by guanglinlv** [comment]
if you are using [openresty](http://openresty.org/en/download.html), you only need to add the `ngx_http_dyups_module` while compiling openresty.

`configure --with-luajit -j2 --add-module=../ngx_http_dyups_module-0.2.9`

then set your nginx configuration like this:

```
server {
    listen 80;
    location / {
        dyups_interface;
 
        content_by_lua_block {
             -- paste your lua code here
        }
   }
}
```

**Comment by guozhouwei** [comment]
platform: macosx (darwin)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20151219
make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-beta1 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
make[1]: Nothing to be done for `default'.
==== Successfully built LuaJIT 2.1.0-beta1 ====
make install TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit DESTDIR=/Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root/
==== Installing LuaJIT 2.1.0-beta1 to /usr/local/openresty/luajit ====
mkdir -p /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/bin /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/include/luajit-2.1 /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/share/man/man1 /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/pkgconfig /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/share/luajit-2.1.0-beta1/jit /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/share/lua/5.1 /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/lua/5.1
cd src && install -m 0755 luajit /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/bin/luajit-2.1.0-beta1
cd src && test -f libluajit.a && install -m 0644 libluajit.a /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.a || :
rm -f /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.2.1.0.dylib /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.dylib /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.2.dylib
cd src && test -f libluajit.so && \
	  install -m 0755 libluajit.so /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.2.1.0.dylib && \
	  : /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib && \
	  ln -sf libluajit-5.1.2.1.0.dylib /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.dylib && \
	  ln -sf libluajit-5.1.2.1.0.dylib /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/libluajit-5.1.2.dylib || :
cd etc && install -m 0644 luajit.1 /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/share/man/man1
cd etc && sed -e "s|^prefix=.*|prefix=/usr/local/openresty/luajit|" -e "s|^multilib=.*|multilib=lib|" luajit.pc > luajit.pc.tmp && \
	  install -m 0644 luajit.pc.tmp /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/lib/pkgconfig/luajit.pc && \
	  rm -f luajit.pc.tmp
cd src && install -m 0644 lua.h lualib.h lauxlib.h luaconf.h lua.hpp luajit.h /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/include/luajit-2.1
cd src/jit && install -m 0644 bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua dis_x86.lua dis_x64.lua dis_arm.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua vmdef.lua /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/share/luajit-2.1.0-beta1/jit
ln -sf luajit-2.1.0-beta1 /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root//usr/local/openresty/luajit/bin/luajit
==== Successfully installed LuaJIT 2.1.0-beta1 to /usr/local/openresty/luajit ====
export LUAJIT_LIB='/Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/lib'
export LUAJIT_INC='/Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1'
cd ..
cd nginx-1.9.7
sh ./configure --prefix=/usr/local/openresty/nginx \
  --with-cc-opt='-O2' \
  --add-module=../ngx_devel_kit-0.2.19 \
  --add-module=../echo-nginx-module-0.58 \
  --add-module=../xss-nginx-module-0.05 \
  --add-module=../ngx_coolkit-0.2rc3 \
  --add-module=../set-misc-nginx-module-0.29 \
  --add-module=../form-input-nginx-module-0.11 \
  --add-module=../encrypted-session-nginx-module-0.04 \
  --add-module=../srcache-nginx-module-0.30 \
  --add-module=../ngx_lua-0.9.20 \
  --add-module=../ngx_lua_upstream-0.04 \
  --add-module=../headers-more-nginx-module-0.29 \
  --add-module=../array-var-nginx-module-0.04 \
  --add-module=../memc-nginx-module-0.16 \
  --add-module=../redis2-nginx-module-0.12 \
  --add-module=../redis-nginx-module-0.3.7 \
  --add-module=../rds-json-nginx-module-0.14 \
  --add-module=../rds-csv-nginx-module-0.07 \
  --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib' \
  --with-openssl=/Users/helloworld/openresty/servers/bundle/openssl-1.0.2g --with-http_ssl_module --with-http_sub_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre=/Users/helloworld/pcre/pcre-8.37 --add-module=/Users/helloworld/openresty/servers/openresty-1.9.7.4/ngx_http_dyups_module
checking for OS
 + Darwin 15.4.0 x86_64
checking for C compiler ... found
 + using Clang C compiler
 + clang version: 7.3.0 (clang-703.0.31)
checking for --with-ld-opt="-Wl,-rpath,/usr/local/openresty/luajit/lib" ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... not found
checking for Darwin specific features
 + kqueue found
checking for kqueue's EVFILT_TIMER ... found
checking for Darwin 64-bit kqueue millisecond timeout bug ... not found
checking for sendfile() ... found
checking for atomic(3) ... found
checking for nobody group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for crypt() ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... not found
checking for O_DIRECT ... not found
checking for F_NOCACHE ... found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... found
checking for sched_yield() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for TCP_DEFER_ACCEPT ... not found
checking for TCP_KEEPIDLE ... not found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... not found
checking for accept4() ... not found
checking for eventfd() ... not found
checking for eventfd() (SYS_eventfd) ... not found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... not found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found but is not working
checking for System V shared memory ... found
checking for POSIX semaphores ... found but is not working
checking for POSIX semaphores in libpthread ... found but is not working
checking for POSIX semaphores in librt ... not found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in ../ngx_devel_kit-0.2.19
 + ngx_devel_kit was configured
adding module in ../echo-nginx-module-0.58
 + ngx_http_echo_module was configured
adding module in ../xss-nginx-module-0.05
 + ngx_http_xss_filter_module was configured
adding module in ../ngx_coolkit-0.2rc3
 + ngx_coolkit_module was configured
adding module in ../set-misc-nginx-module-0.29
found ngx_devel_kit for ngx_set_misc; looks good.
 + ngx_http_set_misc_module was configured
adding module in ../form-input-nginx-module-0.11
found ngx_devel_kit for ngx_form_input; looks good.
 + ngx_http_form_input_module was configured
adding module in ../encrypted-session-nginx-module-0.04
 + ngx_http_encrypted_session_module was configured
adding module in ../srcache-nginx-module-0.30
 + ngx_http_srcache_filter_module was configured
adding module in ../ngx_lua-0.9.20
checking for LuaJIT library in /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/lib and /Users/helloworld/openresty/servers/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 (specified by the LUAJIT_LIB and LUAJIT_INC env, with -ldl) ... found
adding extra linking options needed by LuaJIT
checking for export symbols by default (-E) ... not found
checking for export symbols by default (--export-all-symbols) ... not found
checking for SO_PASSCRED ... not found
 + ngx_http_lua_module was configured
adding module in ../ngx_lua_upstream-0.04
 + ngx_http_lua_upstream_module was configured
adding module in ../headers-more-nginx-module-0.29
 + ngx_http_headers_more_filter_module was configured
adding module in ../array-var-nginx-module-0.04
found ngx_devel_kit for ngx_array_var; looks good.
 + ngx_http_array_var_module was configured
adding module in ../memc-nginx-module-0.16
 + ngx_http_memc_module was configured
adding module in ../redis2-nginx-module-0.12
 + ngx_http_redis2_module was configured
adding module in ../redis-nginx-module-0.3.7
 + ngx_http_redis_module was configured
adding module in ../rds-json-nginx-module-0.14
 + ngx_http_rds_json_filter_module was configured
adding module in ../rds-csv-nginx-module-0.07
 + ngx_http_rds_csv_filter_module was configured
adding module in /Users/helloworld/openresty/servers/openresty-1.9.7.4/ngx_http_dyups_module
 + dyups module support lua
 + ngx_http_dyups_module was configured
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using PCRE library: /Users/helloworld/pcre/pcre-8.37
  + using OpenSSL library: /Users/helloworld/openresty/servers/bundle/openssl-1.0.2g
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library

  nginx path prefix: "/usr/local/openresty/nginx"
  nginx binary file: "/usr/local/openresty/nginx/sbin/nginx"
  nginx configuration prefix: "/usr/local/openresty/nginx/conf"
  nginx configuration file: "/usr/local/openresty/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/openresty/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/openresty/nginx/logs/error.log"
  nginx http access log file: "/usr/local/openresty/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

cd ../..
Type the following commands to build and install:
    make
    make install

**Comment by guanglinlv** [comment]
yeah, your configure log is ok, you should set `dyups_interface` directive as my given examples. let it as the first line in your location.

**Comment by guozhouwei** [comment]
@guanglinlv 

server {
    listen 80;
    location / {
        dyups_interface;

        content_by_lua_block {
             -- paste your lua code here
        }
   }
}

您的意思是 dyups_interface要在lua文件之前写？ 有require的左右。。。 我写在了lua代码之后。。。 

我还有个问题就是这个upstream配置保存在那个文件里面，应该是不在内存了吧？ 因为我需要把upstream的信息存储到redis中。

**Comment by guanglinlv** [comment]
> 您的意思是 dyups_interface要在lua文件之前写？ 有require的左右。。。 我写在了lua代码之后。。。

yes, do you fix the problem that miss module `ngx.dyups` ?

> 问题一：
我还有个问题就是这个upstream配置保存在那个文件里面，应该是不在内存了吧？ 因为我需要把upstream的信息存储到redis中。
问题二：
local status, rv = dyups.update("test", [[server 127.0.0.1:8088;]]);
代码中"test" 这个upstream 文件存放位置是哪？

absolutely, it is in the shared memory. that's why we can update the upstream dynamically. what do you mean you want to save the upstream into redis? maybe you means get the upstream information form redis and update it in the nginx ?

> 最下面两个村upstream文件的接口，用lua 怎么调用呢？ 有demo 吗 ？

i'm  afraid that only `update` and `delete` is all of the available lua interface.

**Comment by guozhouwei** [comment]
@guanglinlv 

现在我有个想法：
我的业务场景：
我的每个nginx 进程是绑定系统的守候进程的，当我的nginx异常挂掉之后，系统守候进程就会再次拉起我的nginx进程，就需要重新加载upstream文件里的分流配置。
我是基于ngx_http_dyups_module动态配置upsteam，如果nginx挂了之后配置就消失了，我就需要实时存储upstream信息，因为我这里上nginx的集群，每个nginx的uptream配置是一样的，我就想把upstream存储到redis上，但是redis也不是绝对安全的，我还希望每个nginx都会生成一个upstream文件，是不是我只能自己实现了？

**Comment by guanglinlv** [comment]
@guozhouwei , you cant post a topic in [`openresty.cn`](https://groups.google.com/forum/#!forum/openresty), there are some similar scenario as yours.

**Comment by guozhouwei** [comment]
@guanglinlv 
还有一个问题：

server {
        	listen 8081;
        	location / {
			dyups_interface;
			content_by_lua_file '../admin/upstream/save.lua'; 
        	}
｝

我再调用：curl 127.0.0.1:8081/detail

就无法展示upstream信息了。。。。
why？

**Comment by ericchenth** [comment]
@guozhouwei 
You can use lua share dict. to store drupes upstream config. Then update upstream config in init_worker_by_lua phase.
