### ISSUE TITLE
Completely not work on openresty 1.9.7.4

### ISSUE THREAD

**Issue by wzxjohn** [yzprofile/ngx_http_dyups_module#56]
After I upgrade openresty to 1.9.7.4, this module will be completely not work.
The web api is still fine and can return the correct message, and if I use lua-upstream-nginx-module to get the upstream info, it seems all fine. But actually, when a request came into my server, nginx will still send it to old upstream, not the new one.

**Comment by yzprofile** [comment]
Please take a look this issue: https://github.com/yzprofile/ngx_http_dyups_module/issues/43

If it's not help. please paste you config file .

Thanks

**Comment by wzxjohn** [comment]
It works! Thank you very much. By the way, maybe you should update the readme to notice users about this.
