### ISSUE TITLE
是否可以获取upstream的更多细节信息

### ISSUE THREAD

**Issue by zheng-ji** [yzprofile/ngx_http_dyups_module#61]
感谢作者开源。请问下：
我想将内存中的upstream 落地保存到配置文件中，请问有什么好的方法吗？

通过

```
curl localhost:port/detail
```

得到的仅有ip,不能满足获取weight=xxx 之类的信息

**Comment by yzprofile** [comment]
You can use this module `https://github.com/agentzh/lua-upstream-nginx-module` to get more details.

**Comment by chobits** [comment]
It has been fixed in latest master branch. See this pull request: https://github.com/yzprofile/ngx_http_dyups_module/pull/52.

For example:

```
» curl 127.0.0.1:8081/detail
host1
server 127.0.0.1:8088

host2
server 127.0.0.1:8089

dyhost
server 127.0.0.1:8089
server 127.0.0.1:8088

```

**Comment by chobits** [comment]
I'm closing this issue, feel free to reopen.
