### ISSUE TITLE
module 'ngx.dyups' not found  请指教～

### ISSUE THREAD

**Issue by guozhouwei** [yzprofile/ngx_http_dyups_module#62]
**# 1. 错误信息：**
==> error.log <==
2016/07/06 16:41:21 [error] 23688#0: *77979 lua entry thread aborted: runtime error: /data/abtesting/navigator/utils/../admin/upstream/build.lua:8: module 'ngx.dyups' not found:
	no field package.preload['ngx.dyups']
	no file '../lib/ngx/dyups.lua'
	no file './ngx/dyups.lua'
	no file '/usr/local/share/luajit-2.0.4/ngx/dyups.lua'
	no file '/usr/local/share/lua/5.1/ngx/dyups.lua'
	no file '/usr/local/share/lua/5.1/ngx/dyups/init.lua'
	no file './ngx/dyups.so'
	no file '/usr/local/lib/lua/5.1/ngx/dyups.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './ngx.so'
	no file '/usr/local/lib/lua/5.1/ngx.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/data/abtesting/navigator/utils/../admin/upstream/build.lua:8: in function </data/abtesting/navigator/utils/../admin/upstream/build.lua:1>, client: 127.0.0.1, server: localhost, request: "POST /admin/upstream/build HTTP/1.1", host: "127.0.0.1:8081"

**# 2. tengine 编译命令**
 cd tengine-2.1.2
 ./configure --prefix=/opt/nginx \
--lock-path=/var/lock/nginx.lock \
--pid-path=/var/run/nginx.pid \
--error-log-path=/data/log/nginx/error.log \
--http-log-path=/data/log/nginx/access.log \
--user=nobody \
--group=nobody \
--with-pcre=../pcre-8.36 \
--with-pcre-opt=-fPIC \
--with-openssl=../openssl-1.0.1m \
--with-openssl-opt=-fPIC \
--with-backtrace_module \
--with-http_stub_status_module \
--with-http_gzip_static_module \
--with-http_realip_module \
--with-http_concat_module=shared \
--with-http_sysguard_module=shared \
--with-http_limit_conn_module=shared \
--with-http_limit_req_module=shared \
--with-http_split_clients_module=shared \
--with-http_footer_filter_module=shared \
--with-http_geoip_module=shared \
--with-http_sub_module=shared \
--with-http_access_module=shared \
--with-http_upstream_ip_hash_module=shared \
--with-http_upstream_least_conn_module=shared \
--with-http_referer_module=shared \
--with-http_rewrite_module=shared \
--with-http_memcached_module=shared \
--with-http_upstream_session_sticky_module=shared \
--with-http_addition_module=shared \
--with-http_user_agent_module=shared \
--with-http_empty_gif_module=shared \
--with-http_browser_module=shared \
--with-http_map_module=shared \
--with-http_userid_filter_module=shared \
--with-http_charset_filter_module=shared \
--with-http_trim_filter_module=shared \
--with-http_lua_module=shared \
--with-http_reqstat_module=shared \
--with-http_v2_module \
--with-http_dyups_module \
--with-http_fastcgi_module=shared \
--with-http_uwsgi_module=shared \
--with-http_scgi_module=shared \
--without-select_module \
--without-poll_module \
--http-client-body-temp-path=/data/nginx_temp/nginx_client \
--http-proxy-temp-path=/data/nginx_temp/nginx_proxy \
--http-fastcgi-temp-path=/data/nginx_temp/nginx_fastcgi
 make
 make install DESTDIR=/tmp/tengine_bin
 make install

**# 3 疑问：**
我已经在location 写了dyups_interface; 从tengine编译命令中是不是因为 我的luajit，http_dyups_lua_api，ndk 没加引起的 ？ 因为这个命令是公司的标配，所以我暂时没办法尝试，请指教～

**Comment by yzprofile** [comment]
https://github.com/alibaba/tengine/issues/760
