### ISSUE TITLE
dyups模块添加upstream到内存后 reload 如何持久化upstream配置的问题

### ISSUE THREAD

**Issue by zousheng** [yzprofile/ngx_http_dyups_module#65]
请问tengine添加了dyups模块以后，动态把upstream加载到内存以后，如果reload tengine,之前通过dyups restful api添加的upstream会消失， 不知道这个你们有没有好的持久化方案？不知道是不是我的使用方式不对。

请多多指教。  多谢！

**Comment by zousheng** [comment]
已经从楼主那里得到答案了， 可以在share_dict里或者先写到配置文件里

**Comment by xujingbin** [comment]
@zousheng share_dict是什么，
