### ISSUE TITLE
not able to use dyups module to forward a request to dymanically updated upstream

### ISSUE THREAD

**Issue by hkmo** [yzprofile/ngx_http_dyups_module#66]
Hi

I would like to use this module dyups, but I have some troubles. The request is not forwarded to the upstream.

location / {
  dyups_interface;

  content_by_lua '
    local dyups = require "ngx.dyups"
    local status, rv = dyups.update("test", [[server 144.134.124.36:8080;]]);
    print(status, rv)
    if status ~= ngx.HTTP_OK then
        ngx.print(status, rv)
        return
    end
    ngx.print("update success")
     ';
}

when I send a request that is resolved to the above location "/", my server 144.134.124.36:8080 is not receiving anything.
My question, is how can you proxy to an upstream server that you dynamically add in the above lua script?

Thanks

**Comment by yzprofile** [comment]
```
    server {
        listen   8080;
        location / {
            set $ups test;
            # The upstream here must be a nginx variable
            proxy_pass http://$ups; 
        }
    }
```

you need to use variable to do proxy.

**Comment by hkmo** [comment]
I am not sure I understand. How would you set this variable with a real upstream name? and how would you change dynamically the servers in that upstream? 
Let's say we have the following upstream example:
 upstream dynamic {
    server 127.0.0.1:8081;
    keepalive 10;
  }
I want to dynamically add a new server in that upstream when I hit the below location:
server {
  listen 8080;
  location / {
      dyups_interface;

     ## how do I update dynamically the upstream "dynamic" here? 
    proxy_pass http://dynamic;
 }

Thanks

**Comment by yzprofile** [comment]
```
upstream dynamic {
server 127.0.0.1:8081;
keepalive 10;
}
I want to dynamically add a new server in that upstream when I hit the below location:
server {
listen 8080;
location / {
dyups_interface;

 ## how do I update dynamically the upstream "dynamic" here? 
set $ups dynamic;
proxy_pass http://$ups;
}
```
