### ISSUE TITLE
我尝试通过restful接口去访问，提示我success，但是并没有及时更新过来。

### ISSUE THREAD

**Issue by mliu111477** [yzprofile/ngx_http_dyups_module#68]
一下为nginx的相关配置：
server {
        listen   8080;
        location / {
           dyups_interface;
        }
    }

server {
        listen       80;
        
        location /test {
            set $upstream "dubbo";
            proxy_pass http://$upstream;
        }
}

我执行如下语句:
curl -d "server 127.0.0.1:801;server 127.0.0.1:802;" localhost:8080/upstream/dubbo

在我执行更新方法的时候，日志信息会如下提示：
2016/11/09 14:07:25 [info] 21190#0: *366 [dyups] post upstream name: dubbo, client: 127.0.0.1, server: , request: "POST /upstream/dubbo HTTP/1.1", host: "localhost:8080"
2016/11/09 14:07:25 [debug] 21190#0: [dyups] upstream reuse, idx: [0]
2016/11/09 14:07:25 [info] 21190#0: [dyups] delete upstream "_dyups_upstream_sandbox_"
2016/11/09 14:07:25 [debug] 21190#0: [dyups] find upstream idx: 0 ref: 0 on _dyups_upstream_sandbox_ deleting
2016/11/09 14:07:25 [info] 21190#0: [dyups] free dynamic upstream in find upstream 0
2016/11/09 14:07:25 [debug] 21190#0: [dyups] upstream reuse, idx: [1]
2016/11/09 14:07:25 [debug] 21190#0: [dyups] upstream delete first
2016/11/09 14:07:25 [info] 21190#0: [dyups] delete upstream "dubbo"
2016/11/09 14:07:25 [debug] 21190#0: [dyups] find upstream idx: 1 ref: 0 on dubbo deleting
2016/11/09 14:07:25 [info] 21190#0: [dyups] free dynamic upstream in find upstream 1
2016/11/09 14:07:25 [debug] 21190#0: [dyups] find another, idx: [1]
2016/11/09 14:07:25 [info] 21190#0: *366 client 127.0.0.1 closed keepalive connection

**# 这时候我在访问localhost/test应该会报错才对(没有这两个地址)，但是没有报错！还是之前的信息！**

**Comment by yzprofile** [comment]
请把完整配置贴出，已经复现流程。谢谢

**Comment by mliu111477** [comment]
编译脚本：./configure --with-http_lua_module --add-module=/usr/local/software/nginx-plugins/ngx_http_dyups_module

nginx.conf：
worker_processes  1;

events {
    worker_connections  1024;
}

dso {
    #load ngx_http_dyups_module.so;
    #load ngx_http_lua_upstream_module.so;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    lua_code_cache off;
    lua_shared_dict xconf_cache 10m;
    init_by_lua_file xconf/on_init_nginx.lua;

    upstream dubbo{
        server zk1:8081;
        server zk2:8080;
        server zk3:8080;
    }

    server {
        listen 8888;
        location / {
            dyups_interface;
        }
    }
	
	server {
        listen       80;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        location /test {
            set $upstream "dubbo";
            proxy_pass http://$upstream;
        }


        location /changeUps {
            default_type text/html;

            content_by_lua '
                local dyups = require "ngx.dyups"

                local status, rv = dyups.update("dubbo", [[server zk1:8081;]]);
                ngx.say(status);
            ';
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
	}


}

**Comment by mliu111477** [comment]
log相关内容(重复部分没有贴出，都是dyups每秒的日志信息)：
2016/11/11 10:15:52 [alert] 20591#0: lua_code_cache is off; this will hurt performance in /usr/local/nginx/conf/nginx.conf:22
2016/11/11 10:15:52 [notice] 20591#0: using the "epoll" event method
2016/11/11 10:15:52 [notice] 20591#0: nginx/1.6.2
2016/11/11 10:15:52 [notice] 20591#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
2016/11/11 10:15:52 [notice] 20591#0: OS: Linux 3.10.0-327.36.3.el7.x86_64
2016/11/11 10:15:52 [notice] 20591#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2016/11/11 10:15:52 [notice] 20592#0: start worker processes
2016/11/11 10:15:52 [notice] 20592#0: start worker process 20593
2016/11/11 10:15:52 [notice] 20592#0: start procs processes
2016/11/11 10:15:53 [info] 20593#0: [dyups] has 1 upstreams, 0 static, 0 deleted, all 1
2016/11/11 10:15:54 [info] 20593#0: [dyups] has 1 upstreams, 0 static, 0 deleted, all 1
2016/11/11 10:16:58 [info] 20593#0: *247 [dyups] post upstream name: dubbo, client: 10.211.55.2, server: , request: "POST /upstream/dubbo HTTP/1.1", host: "zk1:8888"
2016/11/11 10:16:58 [info] 20593#0: [dyups] create upstream _dyups_upstream_sandbox_
2016/11/11 10:16:58 [info] 20593#0: [dyups] delete upstream "_dyups_upstream_sandbox_"
2016/11/11 10:16:58 [debug] 20593#0: [dyups] upstream reuse, idx: [0]
2016/11/11 10:16:58 [debug] 20593#0: [dyups] upstream delete first
2016/11/11 10:16:58 [info] 20593#0: [dyups] delete upstream "dubbo"
2016/11/11 10:16:58 [debug] 20593#0: [dyups] find upstream idx: 0 ref: 0 on dubbo deleting
2016/11/11 10:16:58 [info] 20593#0: [dyups] free dynamic upstream in find upstream 0
2016/11/11 10:16:58 [debug] 20593#0: [dyups] find upstream idx: 1 ref: 0 on _dyups_upstream_sandbox_ deleting
2016/11/11 10:16:58 [info] 20593#0: [dyups] free dynamic upstream in find upstream 1
2016/11/11 10:16:58 [debug] 20593#0: [dyups] find another, idx: [1]
2016/11/11 10:16:59 [info] 20593#0: [dyups] has 1 upstreams, 0 static, 1 deleted, all 2

**Comment by yzprofile** [comment]
fixed: https://github.com/yzprofile/ngx_http_dyups_module/commit/766fe0604e88c20a21ee29f154401c16cbaccc4d.

thanks for your report. issue close.
