### ISSUE TITLE
请问能否跟ngx_http_upstream_session_sticky_module一起使用？

### ISSUE THREAD

**Issue by freexp** [yzprofile/ngx_http_dyups_module#69]
```
upstream host1{
    session_sticky;
    server 127.0.0.1:10001;
    server 127.0.0.1:10002;
    server 127.0.0.1:10003;
}
```
固定的地址，session_sticky有效。通过restful接口更新，server列表更新后，就没有session粘连了。

**Comment by yzprofile** [comment]
I will test it latter. thanks for your report.

**Comment by freexp** [comment]
curl -d "session_sticky; server 127.0.0.1:8080;server 127.0.0.1:9090;" 127.0.0.1:8081/upstream/host1

it works.

**Comment by yzprofile** [comment]
ok. ISSUE Close?
