### ISSUE TITLE
lua api 方法

### ISSUE THREAD

**Issue by myselfghost** [yzprofile/ngx_http_dyups_module#70]
lua api方法只有update,没有add等，操作不方便。

**Comment by yzprofile** [comment]
update 一个不存在的等同于 add

**Comment by myselfghost** [comment]
我指的是同一个upstream里面的server，每次update同一个upstream的 server的时候，原来的就覆盖了。

**Comment by yzprofile** [comment]
因为upstream并不是持久性的，最终一致性以及接口的易用性需要由其他系统或模块来保证，dyups 模块只提供最基础的功能。

**Comment by myselfghost** [comment]
lua api方法update,是每个work都要执行，还是只需一个work执行全部有效啊？

**Comment by yzprofile** [comment]
只需要 一个 worker 执行

**Comment by myselfghost** [comment]
谢谢啦
