### ISSUE TITLE
dyups.update 覆盖原配置文件的内容

### ISSUE THREAD

**Issue by myselfghost** [yzprofile/ngx_http_dyups_module#73]
lua api方法，dyups.update 会覆盖原来的配置文件中，upstream {} 中的内容吗？
比如原来配置文件 upstream {} 中有：
upstream {
keepalive 16;
}
使用 dyups.update("test", [[server 127.0.0.1:8088;]]) 之后，原来的keepalive 16; 就不存在了。

**Comment by yzprofile** [comment]
```bash
dyups.update("test", [[server 127.0.0.1:8088; keepalive 16;]])
```

需要使用这个指令

**Comment by myselfghost** [comment]
那就是全覆盖了哦

**Comment by yzprofile** [comment]
是的
