### ISSUE TITLE
How to close some logs?

### ISSUE THREAD

**Issue by XadillaX** [yzprofile/ngx_http_dyups_module#76]
How to close off logs like:

```
2017/02/22 16:53:01 [info] 64215#0: [dyups] has 0 upstreams, 0 static, 0 deleted, all 0
```

I want to debug my own program in `error.log` with info level but dyups writes info logs every second.

**Comment by yzprofile** [comment]
use the hight log level.

**Comment by XadillaX** [comment]
But I want debug my own code. That means my own lua code use info or debug level log.

**Comment by XadillaX** [comment]
Could you please add a new command like:

```nginx
dyups_read_msg_log off;
```
