### ISSUE TITLE
一个和upstream_check兼容性的问题

### ISSUE THREAD

**Issue by JHsorth** [yzprofile/ngx_http_dyups_module#78]
十分感谢，请教一个和upstream_check兼容性问题
编译参数:
nginx version: openresty/1.11.2.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --user=www --group=www --with-http_stub_status_module --with-google_perftools_module --with-http_ssl_module --add-module=../ngx_http_dyups_module --add-module=../nginx_upstream_check_module

想使用dyups + upstream_check 
线上的upstream_check原先是 yaoweibin 的  打的patch  check_1.11.1.patch 使用正常
我将 yzprofile upstream_check模块中的源码 覆盖了 yaoweibin 的源码
并且打的patch是 check_1.11.1.patch

编译安装正常，但在启动时报错
nginx: [warn] invalid directive "dyups_upstream_conf" of ngx_http_dyups_module, it has been deprecated in /usr/local/openresty/nginx/conf/nginx.conf:66

请问下 这可能是哪里的问题呢？

**Comment by yzprofile** [comment]
这个只是一个接口废弃了的提醒，并不影响使用。
