### ISSUE TITLE
Is it able to persist upstreams?

### ISSUE THREAD

**Issue by runningship** [yzprofile/ngx_http_dyups_module#81]
It seems dynamicly added upstream lost when restart nginx.
so is it able to persist upstreams?

**Comment by yzprofile** [comment]
no

**Comment by iandyh** [comment]
When you are adding the upstream to nginx, just to ensure write to nginx.conf as well.

**Comment by yzprofile** [comment]
No plan to do that.

**Comment by iandyh** [comment]
@yzprofile I am telling the author of this issue. :)
