### ISSUE TITLE
Problem when i try to persist the upstream

### ISSUE THREAD

**Issue by lonelili** [yzprofile/ngx_http_dyups_module#82]
1. the api "/upstream/name" does not have the detail info
when i update one upstream, i'll save the content in a conf file, but localhost/upstream/name doesn't return the detail info. 
So i can only use localhost/detail, which return all upstream detail. And the full info is about 35Kb, which contains too much redundant info.

2. upstream persistence is a basic need, why your team choose not to support? What your advise to deal with this need.
If i want to use dyups_module in production env, the conf persistence is a basic need. Because if nginx reload or restart, the config is gone.

**Comment by yzprofile** [comment]
It's not a good idea to dump upstream to file in nginx, the dyups module is only an `action module`.
you need another software to tell `dyups module` to add/del upstream, and persist it. not rely on a program which is written by `c`

**Comment by lonelili** [comment]
Yes, you're right.
I have a software to check the change of service's route, then tell dyups to add/del upstream, and persist it.
My question is, any upstream change, i should get the whole upstream info by localhost/detail, because the localhost/upstream/name doesn't have enough info. I need a api to get a single upstream full info.

In addition, in production env, a software for persist upstream is necessary, if the dyups module have this function, the user will be more convenient to use. “the dyups module is only an action module”, is it because of this orientation, so you are not plan to do this freature.

**Comment by lonelili** [comment]
![dyups](https://cloud.githubusercontent.com/assets/4277623/26342297/187f7578-3fca-11e7-92d0-a8b43a4fe9af.png)

**Comment by lonelili** [comment]
![dyups](https://cloud.githubusercontent.com/assets/4277623/26342734/c9d095b8-3fcb-11e7-879b-c344cc9547d1.png)

**Comment by lonelili** [comment]
Sorry, i'm stuck in a wrong logic.
My current persist logic is:
1.check for service route change
2.use dyups to update upstream
3.use dyups to search the upstream info
4.save the results of the previous query

The right logic should be:
1.check for service route change
2.use dyups to update upstream
3.save the info used in step2

I do not need to search the upstream info before save.
This issue may confused to you, i'll close the issue.
Thanks.

**Comment by yzprofile** [comment]
😄
