### ISSUE TITLE
Why we must use nginx variable to do proxy_pass？

### ISSUE THREAD

**Issue by lonelili** [yzprofile/ngx_http_dyups_module#83]
If don't use variable, update is still effective, but add a upstream by dyups will not take effect. Am i right?

**Comment by msanjay94** [comment]
Have the same doubt. Can anyone please clarify ?

**Comment by Frodox** [comment]
@yzprofile ?

**Comment by yzprofile** [comment]
the upstream added by `dyups` mod is not indexed by nginx static upstream config.

nginx will find upstream for every request  in proxy_pass handler if we use variable.
