### ISSUE TITLE
转发 URI 到后端会被截断

### ISSUE THREAD

**Issue by coagent** [yzprofile/ngx_http_dyups_module#87]
如下样例配置

```
upstream user_backend {	
	server 192.16.1.100:8080;
	server 192.16.1.101:8080;
}
upstream order_backend {	
	server 192.16.1.100:8082;
	server 192.16.1.101:8082;
}

server {	
        listen 80;
	server_name api.domain.com;
        index index.html default.html;
	set $ups_user_backend user_backend;
	set $ups_order_backend order_backend;

   location /user/{
    	proxy_pass http://$ups_user_backend/user/;
    }
   location /order/{
    	proxy_pass http://$ups_order_backend/order/;
    }
    # ...
}
```

当请求 http://api.domain.com/user/list.html 时，是正常的，如果请求 http://api.domain.com/user/abc/def/info.html , 浏览器收到的内容是 /user/index.html 的内容，而不是 /user/abc/def/info.html，截断了 /abc/def/info.html 这部分 URI。

请问有人遇到吗？如何解决呢？

**Comment by chensunny** [comment]
遇到同样的问题，好像这个项目没更新好久了

**Comment by yzprofile** [comment]
这个配置和 dyups 没有关系，
请好好学习 nginx location 和 proxy_pass 的配置方式。

proxy_pass http://domain.com/;
proxy_pass http://domain.com;

这两种配置的行为模式是不同的
