### ISSUE TITLE
dys upstream如何设置域名

### ISSUE THREAD

**Issue by wondermen** [yzprofile/ngx_http_dyups_module#90]
curl -i -X POST \
   -d \
'server xx.xx.com;' \
 'http://11.165.197.109:8181/upstream/mgs'

设置成功之后，然后查询发现设置的域名在upstream中被解析成了一个地址，如何在upstream中设置域名呢？

**Comment by yzprofile** [comment]
如果要配置域名的话，那也就不需要用到 dyups 模块了，另外nginx原本默认配置在 upstream 里的域名也会被解析成一个 ip。

除非你使用 
set $domainname "taobao.com";
proxy_pass http://$domainname;
这种方式配置

**Comment by wondermen** [comment]
thks
