### ISSUE TITLE
启用proxy_cache用nginx做缓存时，ngx_http_dyups_module 出现 405 API disabled (在线等)

### ISSUE THREAD

**Issue by kidcong** [yzprofile/ngx_http_dyups_module#91]
之前一直用TrafficServer做存储时，用ngx_http_dyups_module模块正常。现在在nginx端启用proxy_cache用nginx做缓存时，ngx_http_dyups_module 模块出现 405 API disabled。
希望帮忙解惑

**Comment by yzprofile** [comment]
"ngx_http_dyups_module 模块出现 405 API disabled" 是啥意思?
