### ISSUE TITLE
compilation error:  v0.2.9 with nginx-1.11.8

### ISSUE THREAD

**Issue by xchkun** [yzprofile/ngx_http_dyups_module#92]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
        -o objs/ngx_modules.o \
        objs/ngx_modules.c
sed -e "s|%%PREFIX%%|/usr/local/nginx|" \
        -e "s|%%PID_PATH%%|/usr/local/nginx/logs/nginx.pid|" \
        -e "s|%%CONF_PATH%%|/usr/local/nginx/conf/nginx.conf|" \
        -e "s|%%ERROR_LOG_PATH%%|/usr/local/nginx/logs/error.log|" \
        < man/nginx.8 > objs/nginx.8
./src/http/modules/ngx_http_dyups_module/ngx_http_dyups_module.c: In function ‘ngx_dyups_init_upstream’:
./src/http/modules/ngx_http_dyups_module/ngx_http_dyups_module.c:1541:9: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘default_port’
     uscf->default_port = 0;
         ^
make[1]: *** [objs/addon/ngx_http_dyups_module/ngx_http_dyups_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/root/nginx/nginx-1.11.8'
make: *** [build] Error 2

the nginx version is nginx-1.11.8

**Comment by takakawa** [comment]
I have met the same question with nginx-1.14.2

**Comment by chobits** [comment]
duplicated, see https://github.com/yzprofile/ngx_http_dyups_module/issues/71

has been fixed in [6fa254d](https://github.com/yzprofile/ngx_http_dyups_module/commit/6fa254dc551d7774a84cc02301ebaf0e59209430)

**Comment by chobits** [comment]
I'm closing this issue, feel free to reopen.
