### ISSUE TITLE
Add support for max_conns 

### ISSUE THREAD

**Issue by iandyh** [yzprofile/ngx_http_dyups_module#95]
Hi. 

Since Nginx 1.11.5, it allows setting max connection per peer in upstream configuration. 

After testing with Nginx 1.13.6, I found the module does not support this new option. The response from server is `add server failed`.

Looking at the source code I cannot find the immediate cause. 

Thanks in advance!
Andy

**Comment by yzprofile** [comment]
https://github.com/yzprofile/ngx_http_dyups_module/pull/97
